name: Bump Version

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  bump_version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Bump Version and Push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          DEFAULT_BUMP: "none"
          GITHUB_TOKEN: ${{ secrets.PAT }}
          WITH_V: true
          MAJOR_STRING_TOKEN: "major:"
          MINOR_STRING_TOKEN: "minor:"
          PATCH_STRING_TOKEN: "fix:"
          BRANCH_HISTORY: "compare"
