name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Initialize Submodules
        run: git submodule init

      - name: Update Submodules
        run: git submodule update

      - name: Build
        run: source ./scripts/build_without_bindings.sh

      - name: Test
        run: source ./scripts/tests.sh
